#!/bin/bash 

# Define inputs - change paths!  
FILES=/to/yor/magma/files/ 
RESULTS=/to/your/magma/results/

mkdir -p $FILES 
mkdir -p $RESULTS 

# Focus on ASD list first
# NOTE: GWAS can be downloaded from PGC: https://pgc.unc.edu/for-researchers/download-results/ 
# You must agree to terms and conditions before downloading, so statistics are not included here. 
gwas=$(iPSYCH-PGC_ASD_Nov2017.gz | cut -f2)
ref=$(cut -f2 files/g/g1000_eur.bim) # can be downloaded from https://ctg.cncr.nl/software/magma 

# Let's try re-aligning the reference file
plink_ref=files/g1000_eur  
REF=files/hg19.fa
OUTDIR=files/g/check_realignment/
mkdir -p $OUTDIR 
cd $OUTDIR 

# Check alignment of magma code 
scripts/align_plink_2.sh $plink_ref $REF $OUTDIR 

# Lots of SNPs are indeed ambiguous 
# Need to install snpflip if you want to re-run: github.com/endrebak/snpflip  
~/scripts/my_awk.pl g1000_eur.checkflip.ambiguous g1000_eur_X_recoded.bim 1 | cut -f5- | sort | uniq -c
# 787214 A	T
# 941947 C	G
# 946028 G	C
# 788468 T	A

# ASD: hg19 
asd_2019=iPSYCH-PGC_ASD_Nov2017.gz
asd_2017=PGC.ASD.euro.all.25Mar2015.txt.gz

# Preprocessing 
mkdir -p $FILES/forMAGMA/
cd $FILES/forMAGMA/ 
for s in $asd_2019 $asd_2017 
    do
	bname=$(basename $s .txt.gz) 
	PVALS_FOR_MAGMA=$FILES/forMAGMA/${bname}.forMAGMA 
	# NOTE: below is a general way to find column indexes.
	i_p=$(zcat $s | head -n1 | tr "\t" "\n" | grep -ni ^p | grep -iv pos | cut -f1 -d":")
	i_s=$(zcat $s | head -n1 | tr "\t" "\n" | grep -ni snp | cut -f1 -d":" )
	zcat $s | cut -f$i_s,$i_p | sed 's/^snpid/SNP/g' | sed 's/SNPID/SNP/g' | sed 's/Pval$/P/g' | sed 's/P.value'/P/g> $PVALS_FOR_MAGMA 
    done 

# Make a sample size key (originally wrote code generally in case I wanted to try more GWASes) 
for s in $asd_2019 $asd_2017 
    do
	bname=$(basename $s .txt.gz) 
	i_N=$(zcat $s | head -n1 | tr "\t" "\n" | grep -ni ":N" | tr "\n" " ") # | cut -f1 -d":")
	echo "$bname $i_N"
    done 
 
# Since only a few GWASes have Neffs, just using N for all analyses where I can find an N...  
# Separate out the bait lists 
baits=files/bait_lists_053023.tsv
OUTDIR=/path/to/outdir/ # Change to your outdir! 
mkdir -p $OUTDIR/separated_lists/ 
for i in $(seq 14)
    do 
	bait=$(cut -f$i $baits | head -n1)
	outfile=$OUTDIR/separated_lists/${bait}.txt
	ntail=$(cut -f$i $baits | grep -iv Bait$ | wc -l )
	cut -f$i $baits | tail -n $ntail | grep -v "^$" > $outfile 
    done
 
# Files downloaded from MAGMA website
# https://ctg.cncr.nl/software/magma 
#ml magma_gwas/1.0.8 # Sinai HPC specific command  
annot=/generated/previously/not/on/github/g1000-NCBI37.3-35kb-10kb.genes.annot # output from collaborator, previously generated. 

# flags to recreate: 
#       magma --annotate window=35,10 --snp-loc g1000.bim --gene-loc NCBI37.3.gene.loc --out g1000-NCBI37.3-35kb-10kb

# Let's run what we can for now
script=scripts/wrap_magma_step2and3.sh
plink_ref=files/g/g1000_eur 
pvals=$FILES/forMAGMA/iPSYCH-PGC_ASD_Nov2017.gz.forMAGMA
N=46351

# Run! 
set_file=files/bait_lists_geneNUMBERS.txt # made in excel, mapped with vlookup, removed extra tabs in vi  
set_name=$(basename $set_file .txt)
OUTDIR=/path/to/magma/out/all_sets/
mkdir -p $OUTDIR 
cd $OUTDIR 
$script $plink_ref $pvals $N $annot $set_file $OUTDIR # originally run on HPC
